version: '3.7'
# ERROR - Removed subprocess.CalledProcessError: 
# Command '['/usr/local/bin/docker-credential-desktop', 'get']' 
# returned non-zero exit status 1

# SOLUTION - Remove "credsStore":"desktop" from ~/.docker/config.json 
# Original Content of ~/.docker/config.json
# {"auths":{},"credsStore":"", "credsStore":"desktop","stackOrchestrator":"swarm"}
# Update it to this
# {"auths":{},"credsStore":"","stackOrchestrator":"swarm"}
# OR
# {"auths":{},"stackOrchestrator":"swarm"}
networks:
  fullstack-net:

services:

  todo-frontend:
#    image: frontfinal/frontfinal
    build:
      context: frontend/todo-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: always
    depends_on: # Start the depends_on first
      - todo-api 
    networks:
      - fullstack-net

  todo-api:
#    image: backfinal:backfinal
    build:
      context: restful-web-services/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - fullstack-net