version: '3.7'

networks:
  currency-compose-network:

services:
  naming-server:
    build:
      context: netflix-eureka-naming-server/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - currency-compose-network

  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - currency-compose-network

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: always
    environment:
      STORAGE_TYPE: mem
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - currency-compose-network

  zuul-api-gateway:
    build:
      context: netflix-zuul-api-gateway-server/
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network

  currency-exchange-service:
    build:
      context: currency-exchange-service/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network

  currency-converter-service:
    build:
      context: currency-conversion-service/
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    restart: always
    environment:
#      CURRENCY_EXCHANGE_URI: http://currency-exchange-service:8000
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - currency-exchange-service
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network