version: '3.7'

networks:
  currency-compose-network:

services:
  naming-server:
    build:
      context: netflix-eureka-naming-server/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - currency-compose-network

  currency-exchange-service:
    build:
      context: currency-exchange-service/
      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
    restart: always
    depends_on:
      - naming-server
    networks:
      - currency-compose-network

  currency-converter-service:
    build:
      context: currency-conversion-service/
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    restart: always
    environment:
      CURRENCY_EXCHANGE_URI: http://currency-exchange-service:8000
    depends_on:
      - currency-exchange-service
      - naming-server
    networks:
      - currency-compose-network